# Overview

<b> Features: </b>
1. Scale: Min-Max/ Standard Scaling
2. Log Transform

# Notebook Set-Up

In [1]:
import numpy as np

import pandas as pd
pd.set_option('display.float_format', lambda x: '%.3f' % x)           # prevents scientific notation

import warnings
warnings.filterwarnings('ignore')

# Import Data

In [2]:
github = r'https://raw.githubusercontent.com/mattlibonati/Northwestern-MSDS-Capstone-2023/main/Data/'
github_r = r'https://raw.githubusercontent.com/mattlibonati/Northwestern-MSDS-Capstone-2023/main/Data/raw_data/'

# Final Data

In [8]:
pd.set_option('display.max_columns', None)

final = pd.read_csv(github+'final_data.csv')

# output data
print('Raw Data:')             
display(final)               

# Label Encoding
final_strings        = final.select_dtypes(include=['object'])
final_string_encoded = label_encode(final_strings)
final_encoded        = final_string_encoded.join(final.select_dtypes(exclude=['object']))

print('Standard Scaling:')
display(scale_set(final_encoded)[0]) 
print('Min-Max Scaling:')
display(scale_set(final_encoded)[1])
print('Log Transformed:')
display(log_transform(final_encoded))

# output files to excel
scale_set(final_encoded)[0].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\final\final_standard_scaled.csv')
scale_set(final_encoded)[1].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\final\final_minmax_scaled.csv')
log_transform(final_encoded).round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\final\final_log_transformed.csv')
final_encoded.round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\final\final_label_encoded.csv')

scale_set(log_transform(final_encoded).replace([np.inf, -np.inf], 0))[0].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\final\final_log_ss.csv')
scale_set(log_transform(final_encoded).replace([np.inf, -np.inf], 0))[1].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\final\final_log_mm.csv')

Raw Data:

,fips,county_name,state,attained_bachelors,attained_doctorate,attained_masters,attained_professional,black,black_homeowners,eight_rooms,electricity_cost,five_rooms,four_rooms,kitchen_complete,lower_quartile_home_value,mean_household_size_owner,mean_household_size_renter,median_age,median_gross_rent,median_gross_rent_frac_income,median_home_value,median_number_rooms,median_year_built,mhhi,mhhi_family,mhhi_nonfamily,more_than_200k,one_person_household,one_room,owners_25_34,plumbing_complete,renter_occupied,seven_rooms,six_rooms,three_rooms,total_pop,transportation_drive_alone,transportation_public,two_rooms,upper_quartile_home_value,vacant_units,white,unemployed_rate_q1_22,unemployed_rate_q2_22,unemployed_rate_q3_22,unemployed_rate_q4_22,unemployed_rate_year_22,emp_location_quotient_natural_resources_and_mining,emp_location_quotient_construction,emp_location_quotient_manufacturing,emp_location_quotient_trade_transportation_and_utilities,emp_location_quotient_information,emp_location_quotient_financial_activities,emp_location_quotient_professional_and_business_services,emp_location_quotient_education_and_health_services,emp_location_quotient_leisure_and_hospitality,emp_location_quotient_other_services,emp_location_quotient_unclassified,wage_location_quotient_natural_resources_and_mining,wage_location_quotient_construction,wage_location_quotient_manufacturing,wage_location_quotient_trade_transportation_and_utilities,wage_location_quotient_information,wage_location_quotient_financial_activities,wage_location_quotient_professional_and_business_services,wage_location_quotient_education_and_health_services,wage_location_quotient_leisure_and_hospitality,wage_location_quotient_other_services,wage_location_quotient_unclassified,house_price_jan_2022,house_price_feb_2022,house_price_mar_2022,house_price_apr_2022,house_price_may_2022,house_price_jun_2022,house_price_july_2022,house_price_aug_2022,house_price_sep_2022,house_price_oct_2022,house_price_nov_2022,house_price_dec_2022,house_price_jan_2023,house_price_feb_2023,house_price_mar_2023,house_price_avg_q1_2022,house_price_avg_q2_2022,house_price_avg_q3_2022,house_price_avg_q4_2022,house_price_avg_q1_2023,house_price_avg_2022
0,1001,Autauga County,Alabama,0.164,0.012,0.092,0.013,0.197,0.561,0.104,0.008,0.192,0.115,0.993,91400.000,2.720,2.400,38.500,1085.000,25.400,164900.000,6.000,1992,62660.000,72441.000,31338.000,0.047,0.261,0.007,0.136,0.995,0.258,0.160,0.235,0.048,58239,0.864,0.005,0.010,243000.000,0.096,0.731,2.467,2.200,2.467,2.033,2.292,1.290,0.820,1.560,1.080,0.100,0.620,0.440,0.700,1.400,0.860,NaN,2.340,0.910,2.000,1.220,0.070,0.440,0.400,0.750,1.300,0.890,NaN,203508.284,205676.872,207975.239,210756.102,213627.987,216100.356,217490.320,218100.764,218175.253,218405.212,218632.351,218954.011,220077.135,221399.326,223375.816,205720.131,213494.815,217922.112,218663.858,221617.426,213950.229
1,1003,Baldwin County,Alabama,0.206,0.014,0.086,0.019,0.087,0.629,0.098,0.008,0.216,0.151,0.993,151300.000,2.640,2.350,43.400,1093.000,28.900,226600.000,5.800,1996,64346.000,82801.000,35140.000,0.071,0.291,0.013,0.090,0.997,0.229,0.134,0.217,0.050,227131,0.814,0.001,0.012,354100.000,0.284,0.826,2.600,2.233,2.500,2.100,2.358,0.800,1.230,0.560,1.250,0.270,0.970,0.580,0.860,2.000,0.900,NaN,0.930,1.530,0.620,1.440,0.170,0.780,0.480,1.170,2.780,1.260,NaN,322932.652,327953.669,333263.626,338911.168,343878.542,348584.242,351403.930,353147.101,353390.241,353547.403,353692.871,353344.035,353140.634,353350.273,354946.157,328049.982,343791.317,352647.090,353528.103,353812.355,344504.123
2,1005,Barbour County,Alabama,0.067,0.006,0.029,0.009,0.472,0.540,0.060,0.014,0.234,0.167,0.994,44000.000,2.480,2.410,40.200,605.000,25.900,89500.000,5.300,1980,36422.000,48768.000,20704.000,0.033,0.330,0.004,0.101,0.998,0.378,0.122,0.193,0.118,25259,0.831,0.001,0.021,166600.000,0.221,0.446,4.333,3.533,4.167,4.200,4.058,2.880,0.390,3.240,0.890,0.090,0.470,0.410,0.640,0.890,0.540,NaN,4.200,0.540,3.120,1.080,0.050,0.320,0.240,0.740,0.850,0.680,NaN,120942.407,120917.883,120486.866,120376.287,120717.462,121898.647,123191.049,124317.903,124396.337,123950.696,123286.993,123113.493,125473.326,128429.254,131700.087,120782.386,120997.466,123968.429,123450.394,128534.223,122299.669
3,1007,Bibb County,Alabama,0.079,0.004,0.030,0.006,0.219,0.598,0.070,0.002,0.248,0.147,0.984,60200.000,3.030,2.700,39.700,744.000,29.100,102900.000,5.700,1985,54277.000,67979.000,22535.000,0.033,0.271,0.009,0.047,0.993,0.212,0.143,0.242,0.032,22412,0.870,0.000,0.015,174000.000,0.214,0.740,2.667,2.300,2.800,2.267,2.508,1.080,2.620,1.570,1.210,0.000,0.340,0.180,0.730,0.380,0.000,NaN,1.100,3.880,1.530,1.240,0.000,0.170,0.170,0.840,0.310,0.000,NaN,155812.947,157805.467,159430.653,160280.309,161216.550,163468.303,165450.889,166732.571,166448.797,165881.517,165189.797,164670.132,167023.158,169847.900,173319.028,157683.023,161655.054,166210.752,165247.149,170063.362,162698.994
4,1009,Blount County,Alabama,0.093,0.004,0.045,0.007,0.013,0.891,0.097,0.007,0.246,0.129,0.992,79200.000,2.860,2.280,41.100,691.000,27.400,138100.000,5.800,1989,52830.000,68945.000,23818.000,0.037,0.255,0.007,0.109,0.994,0.208,0.134,0.217,0.034,58884,0.864,0.001,0.009,222900.000,0.132,0.859,2.400,2.167,2.367,2.000,2.233,0.620,1.300,1.750,1.030,0.320,0.500,0.360,0.740,1.010,1.240,NaN,0.590,1.500,1.780,1.240,0.230,0.410,0.340,0.860,0.940,1.560,NaN,184019.382,186828.100,190183.062,193478.429,196269.720,198280.486,199263.536,199622.809,199468.619,199202.911,198561.541,197974.348,200420.519,203781.968,207995.497,187010.181,196009.545,199451.655,198579.600,204065.995,195262.745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56037,Sweetwater County,Wyoming,0.124,0.008,0.046,0.016,0.011,0.455,0.083,0.192,0.226,0.153,0.996,134100.000,2.720,2.660,36.400,859.000,22.300,217300.000,5.600,1981,76668.000,93852.000,40691.000,0.051,0.290,0.013,0.117,0.998,0.255,0.109,0.174,0.069,42459,0.768,0.024,0.018,296800.000,0.190,0.783,4.767,3.967,3.900,4.033,4.167,13.500,1.250,0.720,1.080,0.290,0.480,0.350,0.420,1.190,0.760,0.150,27.490,1.190,1.150,1.110,0.100,0.260,0.230,0.290,0.850,0.660,0.160,238307.350,239720.096,241401.498,242800.580,243820.489,244857.951,245768.404,246911.448,247485.676,248251.170,248761.839,249339.024,250256.334,251975.658,254116.022,239809.648,243826.340,246721.843,248784.011,252116.005,244785.460
3139,56039,Teton County,Wyoming,0.383,0.021,0.147,0.028,0.007,0.000,0.064,0.052,0.138,0.176,0.984,508300.000,2.390,2.280,39.600,1524.000,24.400,945300.000,4.900,1989,94498.000,113830.000,68047.000,0.172,0.231,0.064,0.080,1.000,0.407,0.099,0.145,0.147,23319,0.651,0.031,0.060,1595400.000,0.281,0.799,2.433,3.533,1.867,3.267,2.775,0.330,2.210,0.130,0.650,0.490,1.090,0.730,0.370,3.620,1.000,0.210,0.280,1.920,0.070,0.580,0.260,1.460,1.320,0.330,4.740,1.140,0.400,1412320.430,1448041.616,1491316.365,1532612.194,1563668.734,1579543.629,1574347.782,1557038.990,1531363.587,1531419.064,1557725.254,1598020.059,1629062.543,1640300.769,1644961.410,1450559.470,1558608.186,1554250.120,1562388.126,1638108.241,1531451.475
3140,56041,Uinta County,Wyoming,0.123,0.006,0.043,0.008,0.003,0.276,0.119,0.139,0.204,0.211,1.000,114600.000,2.760,2.240,36.300,711.000,22.000,190900.000,5.500,1983,75106.000,84504.000,39598.000,0.034,0.285,0.005,0.121,0.996,0.218,0.119,0.127,0.059,20514,0.792,0.011,0.029,293000.000,0.130,0.870,4.167,3.733,3.633,3.700,3.808,1.430,1.730,0.410,1.170,1.890,0.610,0.300,0.900,1.020,0.410,0.190,3.150,2.350,0.410,1.360,1.200,0.450,0.320,0.950,0.960,0.580,0.530,253478.946,258123.688,263713.511,268823.231,273207.014,277208.577,280199.510,282077.335,283126.077,284210.879,285532.719,285964.280,285856.517,287147.986,290176.395,258438.715,273079.607,281800.974,285235.959,287726.966,274638.814
3141,56043,Washakie County,Wyoming,0.172,0.003,0.072,0.014,0.000,NaN,0.137,0.091,0.194,0.156,1.000,133700.000,2.420,1.860,42.700,621.000,21.000,178700.000,5.800,1972,62271.000,71223.000,31628.000,0.026,0.282,0.004,0.094,1.000,0.279,0.111,0.131,0.083,7768,0.811,0.000,0.018,281600.000,0.123,0.816,4.433,4.033,3.767,3.767,4.000,5.310,1.080,1.500,0.920,0.610,0.640,0.230,0.980,0.830,1.060,0.000,6.550,1.110,1.690,1.150,0.430,0.420,0.180,1.170,0.700,0.920,0.090,211207.665,214058.161,216741.056,219285.661,221867.880,224335.912,226243.196,227502.730,227856.608,228917.056,230009.023,231384.819,232349.945,234047.399,236318.128,214002.294,221829.817,227200.845,230103.633,234238.491,223284.147
3142,56045,Weston County,Wyoming,0.139,0.009,0.028,0.008,0.004,0.000,0.119,0.037,0.184,0.195,0.994,110700.000,2.490,1.770,43.600,726.000,27.200,174500.000,5.700,1977,65566.000,71528.000,34968.000,0.036,0.258,0.003,0.079,0.997,0.130,0.125,0.192,0.064,6891,0.682,0.076,0.015,297400.000,0.197,0.881,3.133,2.700,2.367,2.433,2.658,7.950,0.000,0.000,0.990,0.530,0.490,0.160,0.490,0.840,0.380,0.650,10.210,0.000,0.000,0.890,0.170,0.410,0.210,0.410,0.600,0.420,0.710,199328.969,201218.141,203144.995,205136.181,207039.617,208721.979,209747.389,210581.817,211804.431,213544.800,215478.678,216266.798,215439.478,216181.147,218921.095,201230.702,206965.926,210711.213,215096.759,216847.240,208501.150

Standard Scaling:

,county_name,state,fips,attained_bachelors,attained_doctorate,attained_masters,attained_professional,black,black_homeowners,eight_rooms,electricity_cost,five_rooms,four_rooms,kitchen_complete,lower_quartile_home_value,mean_household_size_owner,mean_household_size_renter,median_age,median_gross_rent,median_gross_rent_frac_income,median_home_value,median_number_rooms,median_year_built,mhhi,mhhi_family,mhhi_nonfamily,more_than_200k,one_person_household,one_room,owners_25_34,plumbing_complete,renter_occupied,seven_rooms,six_rooms,three_rooms,total_pop,transportation_drive_alone,transportation_public,two_rooms,upper_quartile_home_value,vacant_units,white,unemployed_rate_q1_22,unemployed_rate_q2_22,unemployed_rate_q3_22,unemployed_rate_q4_22,unemployed_rate_year_22,emp_location_quotient_natural_resources_and_mining,emp_location_quotient_construction,emp_location_quotient_manufacturing,emp_location_quotient_trade_transportation_and_utilities,emp_location_quotient_information,emp_location_quotient_financial_activities,emp_location_quotient_professional_and_business_services,emp_location_quotient_education_and_health_services,emp_location_quotient_leisure_and_hospitality,emp_location_quotient_other_services,emp_location_quotient_unclassified,wage_location_quotient_natural_resources_and_mining,wage_location_quotient_construction,wage_location_quotient_manufacturing,wage_location_quotient_trade_transportation_and_utilities,wage_location_quotient_information,wage_location_quotient_financial_activities,wage_location_quotient_professional_and_business_services,wage_location_quotient_education_and_health_services,wage_location_quotient_leisure_and_hospitality,wage_location_quotient_other_services,wage_location_quotient_unclassified,house_price_jan_2022,house_price_feb_2022,house_price_mar_2022,house_price_apr_2022,house_price_may_2022,house_price_jun_2022,house_price_july_2022,house_price_aug_2022,house_price_sep_2022,house_price_oct_2022,house_price_nov_2022,house_price_dec_2022,house_price_jan_2023,house_price_feb_2023,house_price_mar_2023,house_price_avg_q1_2022,house_price_avg_q2_2022,house_price_avg_q3_2022,house_price_avg_q4_2022,house_price_avg_q1_2023,house_price_avg_2022
0,-1.629,-1.838,-1.937,0.270,0.297,0.991,0.079,0.761,0.365,0.483,-0.975,-0.437,-0.881,0.231,-0.210,0.488,-0.051,-0.556,1.007,-0.419,-0.045,0.591,0.314,0.285,-0.016,-0.188,-0.022,-0.557,-0.562,1.583,0.087,-0.203,1.037,1.232,-0.554,-0.140,1.024,-0.081,-0.563,-0.136,-0.794,-0.103,-0.994,-1.023,-0.896,-1.099,-1.055,-0.407,-0.137,0.169,0.258,-0.594,0.060,-0.040,-0.252,0.760,0.198,NaN,-0.279,-0.165,0.393,0.212,-0.386,-0.060,0.015,-0.289,0.246,0.073,NaN,-0.062,-0.060,-0.069,-0.073,-0.073,-0.073,-0.073,-0.070,-0.064,-0.058,-0.052,-0.045,-0.040,-0.036,-0.034,-0.071,-0.073,-0.069,-0.052,-0.039,-0.057
1,-1.615,-1.838,-1.937,0.987,0.515,0.791,0.658,-0.007,0.612,0.238,-0.979,0.022,0.025,0.235,0.556,0.185,-0.179,0.356,1.039,0.386,0.533,0.196,0.392,0.393,0.567,0.187,0.587,0.031,-0.258,0.066,0.246,-0.538,0.150,0.727,-0.505,0.366,0.371,-0.238,-0.450,0.596,0.927,0.365,-0.911,-0.996,-0.868,-1.043,-1.001,-0.505,0.455,-0.666,0.849,-0.206,1.066,0.348,0.136,1.826,0.289,NaN,-0.481,0.552,-0.652,0.715,-0.116,0.967,0.245,0.480,1.664,0.729,NaN,0.727,0.734,0.726,0.721,0.719,0.722,0.729,0.744,0.760,0.773,0.782,0.789,0.791,0.793,0.794,0.722,0.721,0.744,0.781,0.789,0.750
2,-1.594,-1.838,-1.937,-1.392,-0.275,-0.983,-0.343,2.686,0.291,-1.129,-0.823,0.387,0.434,0.322,-0.815,-0.421,-0.025,-0.240,-0.885,-0.304,-0.752,-0.794,0.079,-1.403,-1.346,-1.236,-0.371,0.767,-0.747,0.406,0.290,1.198,-0.263,0.065,1.684,-0.238,0.596,-0.256,0.004,-0.640,0.352,-1.509,0.176,0.074,0.499,0.729,0.372,-0.089,-0.758,1.573,-0.402,-0.617,-0.371,-0.123,-0.397,-0.146,-0.524,NaN,-0.012,-0.592,1.241,-0.107,-0.440,-0.423,-0.443,-0.308,-0.185,-0.300,NaN,-0.608,-0.611,-0.624,-0.633,-0.637,-0.638,-0.637,-0.635,-0.635,-0.638,-0.641,-0.640,-0.631,-0.620,-0.610,-0.621,-0.636,-0.636,-0.639,-0.622,-0.624
3,-1.501,-1.838,-1.936,-1.185,-0.474,-0.960,-0.684,0.914,0.500,-0.761,-1.141,0.655,-0.076,-0.525,-0.608,1.662,0.717,-0.333,-0.337,0.431,-0.626,-0.002,0.177,-0.255,-0.266,-1.056,-0.368,-0.359,-0.468,-1.362,-0.044,-0.731,0.463,1.398,-1.075,-0.247,1.098,-0.288,-0.313,-0.591,0.289,-0.056,-0.869,-0.941,-0.622,-0.902,-0.880,-0.449,2.462,0.178,0.710,-0.823,-0.745,-0.759,-0.179,-1.052,-1.743,NaN,-0.456,3.267,0.037,0.258,-0.575,-0.876,-0.644,-0.124,-0.703,-1.506,NaN,-0.378,-0.371,-0.377,-0.386,-0.391,-0.389,-0.384,-0.379,-0.379,-0.380,-0.382,-0.382,-0.371,-0.359,-0.349,-0.382,-0.389,-0.381,-0.381,-0.362,-0.374
4,-1.473,-1.838,-1.936,-0.952,-0.454,-0.494,-0.556,-0.526,1.557,0.218,-1.025,0.616,-0.529,0.082,-0.366,1.018,-0.358,-0.072,-0.546,0.041,-0.296,0.196,0.255,-0.348,-0.212,-0.929,-0.265,-0.658,-0.548,0.693,0.048,-0.777,0.148,0.730,-1.010,-0.138,1.027,-0.240,-0.579,-0.268,-0.466,0.530,-1.036,-1.051,-0.978,-1.127,-1.102,-0.541,0.556,0.328,0.085,-0.092,-0.285,-0.261,-0.155,0.067,1.056,NaN,-0.530,0.517,0.226,0.258,0.046,-0.151,-0.157,-0.088,-0.099,1.261,NaN,-0.191,-0.183,-0.182,-0.180,-0.178,-0.180,-0.182,-0.181,-0.178,-0.175,-0.176,-0.175,-0.163,-0.146,-0.131,-0.192,-0.179,-0.180,-0.176,-0.149,-0.173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,1.323,1.665,1.692,-0.419,-0.073,-0.449,0.329,-0.536,-0.017,-0.290,3.863,0.233,0.080,0.438,0.336,0.488,0.615,-0.947,0.116,-1.132,0.446,-0.200,0.099,1.186,1.187,0.735,0.088,0.006,-0.254,0.941,0.305,-0.231,-0.709,-0.454,0.128,-0.187,-0.233,0.626,-0.125,0.219,0.069,0.153,0.448,0.431,0.280,0.588,0.460,2.032,0.484,-0.532,0.258,-0.161,-0.343,-0.289,-0.930,0.387,-0.027,-0.470,3.329,0.159,-0.250,-0.039,-0.305,-0.604,-0.472,-1.132,-0.185,-0.335,-0.400,0.168,0.161,0.143,0.126,0.111,0.100,0.097,0.104,0.115,0.126,0.134,0.143,0.148,0.156,0.159,0.150,0.112,0.105,0.134,0.152,0.133
3139,1.371,1.665,1.692,4.016,1.243,2.705,1.602,-0.565,-1.657,-0.974,0.168,-1.488,0.676,-0.588,5.118,-0.761,-0.358,-0.351,2.737,-0.649,7.270,-1.585,0.255,2.333,2.310,3.433,3.138,-1.125,2.474,-0.259,0.434,1.533,-1.041,-1.251,2.651,-0.244,-1.757,0.879,2.033,8.778,0.899,0.234,-1.015,0.074,-1.388,-0.059,-0.664,-0.599,1.870,-1.025,-1.236,0.296,1.411,0.763,-1.051,4.703,0.514,-0.426,-0.574,1.002,-1.068,-1.250,0.127,3.022,2.654,-1.059,3.542,0.516,-0.217,7.931,8.011,8.075,8.119,8.131,8.110,8.053,7.995,7.934,8.007,8.217,8.512,8.760,8.874,8.907,7.993,8.120,7.994,8.245,8.832,8.086
3140,1.471,1.665,1.692,-0.435,-0.303,-0.548,-0.495,-0.597,-0.662,0.996,2.465,-0.213,1.548,0.816,0.087,0.640,-0.461,-0.965,-0.467,-1.201,0.199,-0.398,0.138,1.085,0.662,0.627,-0.353,-0.096,-0.650,1.077,0.173,-0.660,-0.357,-1.737,-0.216,-0.253,0.086,0.119,0.425,0.194,-0.483,0.584,0.071,0.239,0.062,0.307,0.170,-0.379,1.177,-0.791,0.571,3.493,0.031,-0.427,0.233,0.085,-0.817,-0.441,-0.162,1.499,-0.811,0.532,2.666,-0.030,-0.214,0.077,-0.080,-0.477,-0.117,0.268,0.280,0.284,0.287,0.289,0.294,0.303,0.316,0.332,0.347,0.361,0.371,0.371,0.377,0.386,0.271,0.290,0.317,0.359,0.375,0.318
3141,1.583,1.665,1.692,0.410,-0.568,0.366,0.140,-0.614,NaN,1.649,1.199,-0.396,0.163,0.816,0.331,-0.648,-1.434,0.226,-0.822,-1.431,0.084,0.196,-0.077,0.260,-0.084,-0.159,-0.535,-0.140,-0.726,0.197,0.434,0.050,-0.639,-1.621,0.569,-0.291,0.328,-0.288,-0.143,0.118,-0.546,0.319,0.239,0.486,0.171,0.363,0.325,0.396,0.238,0.119,-0.298,0.570,0.117,-0.621,0.427,-0.252,0.650,-0.580,0.325,0.066,0.158,0.052,0.586,-0.121,-0.615,0.480,-0.329,0.126,-0.454,-0.011,-0.006,-0.014,-0.020,-0.023,-0.024,-0.020,-0.013,-0.005,0.007,0.018,0.032,0.037,0.044,0.048,-0.017,-0.022,-0.013,0.019,0.040,0.000
3142,1.633,1.665,1.693,-0.170,-0.004,-1.005,-0.418,-0.590,-1.657,1.029,-0.220,-0.592,1.159,0.283,0.037,-0.383,-1.664,0.393,-0.408,-0.005,0.045,-0.002,0.020,0.472,-0.067,0.170,-0.295,-0.607,-0.794,-0.297,0.234,-1.688,-0.162,0.034,-0.061,-0.293,-1.361,2.574,-0.272,0.223,0.135,0.639,-0.576,-0.612,-0.978,-0.762,-0.759,0.923,-1.321,-1.134,-0.054,0.388,-0.314,-0.814,-0.760,-0.235,-0.885,-0.105,0.850,-1.216,-1.121,-0.541,-0.116,-0.151,-0.529,-0.912,-0.425,-0.761,0.021,-0.090,-0.089,-0.100,-0.108,-0.113,-0.117,-0.119,-0.115,-0.102,-0.087,-0.071,-0.062,-0.069,-0.069,-0.062,-0.100,-0.113,-0.112,-0.074,-0.069,-0.091

Min-Max Scaling:

,county_name,state,fips,attained_bachelors,attained_doctorate,attained_masters,attained_professional,black,black_homeowners,eight_rooms,electricity_cost,five_rooms,four_rooms,kitchen_complete,lower_quartile_home_value,mean_household_size_owner,mean_household_size_renter,median_age,median_gross_rent,median_gross_rent_frac_income,median_home_value,median_number_rooms,median_year_built,mhhi,mhhi_family,mhhi_nonfamily,more_than_200k,one_person_household,one_room,owners_25_34,plumbing_complete,renter_occupied,seven_rooms,six_rooms,three_rooms,total_pop,transportation_drive_alone,transportation_public,two_rooms,upper_quartile_home_value,vacant_units,white,unemployed_rate_q1_22,unemployed_rate_q2_22,unemployed_rate_q3_22,unemployed_rate_q4_22,unemployed_rate_year_22,emp_location_quotient_natural_resources_and_mining,emp_location_quotient_construction,emp_location_quotient_manufacturing,emp_location_quotient_trade_transportation_and_utilities,emp_location_quotient_information,emp_location_quotient_financial_activities,emp_location_quotient_professional_and_business_services,emp_location_quotient_education_and_health_services,emp_location_quotient_leisure_and_hospitality,emp_location_quotient_other_services,emp_location_quotient_unclassified,wage_location_quotient_natural_resources_and_mining,wage_location_quotient_construction,wage_location_quotient_manufacturing,wage_location_quotient_trade_transportation_and_utilities,wage_location_quotient_information,wage_location_quotient_financial_activities,wage_location_quotient_professional_and_business_services,wage_location_quotient_education_and_health_services,wage_location_quotient_leisure_and_hospitality,wage_location_quotient_other_services,wage_location_quotient_unclassified,house_price_jan_2022,house_price_feb_2022,house_price_mar_2022,house_price_apr_2022,house_price_may_2022,house_price_jun_2022,house_price_july_2022,house_price_aug_2022,house_price_sep_2022,house_price_oct_2022,house_price_nov_2022,house_price_dec_2022,house_price_jan_2023,house_price_feb_2023,house_price_mar_2023,house_price_avg_q1_2022,house_price_avg_q2_2022,house_price_avg_q3_2022,house_price_avg_q4_2022,house_price_avg_q1_2023,house_price_avg_2022
0,0.044,0.000,0.000,0.376,0.070,0.269,0.121,0.226,0.561,0.473,0.031,0.208,0.206,0.977,0.092,0.306,0.259,0.352,0.357,0.390,0.118,0.474,0.994,0.326,0.283,0.213,0.132,0.351,0.025,0.242,0.986,0.231,0.488,0.642,0.168,0.006,0.870,0.010,0.018,0.091,0.091,0.729,0.103,0.116,0.131,0.105,0.112,0.030,0.057,0.167,0.294,0.014,0.117,0.071,0.212,0.169,0.198,NaN,0.037,0.062,0.229,0.265,0.009,0.095,0.081,0.162,0.067,0.111,NaN,0.079,0.078,0.077,0.077,0.076,0.076,0.076,0.076,0.078,0.079,0.080,0.080,0.080,0.079,0.079,0.078,0.076,0.077,0.079,0.079,0.086
1,0.047,0.000,0.000,0.471,0.083,0.250,0.173,0.100,0.629,0.443,0.030,0.248,0.300,0.977,0.159,0.285,0.248,0.460,0.361,0.474,0.170,0.447,0.996,0.338,0.347,0.256,0.201,0.393,0.046,0.161,0.992,0.201,0.409,0.592,0.173,0.023,0.816,0.002,0.023,0.148,0.324,0.825,0.111,0.119,0.133,0.110,0.117,0.019,0.085,0.060,0.341,0.039,0.183,0.093,0.261,0.242,0.207,NaN,0.015,0.105,0.071,0.313,0.022,0.169,0.098,0.252,0.144,0.158,NaN,0.131,0.130,0.130,0.129,0.129,0.128,0.128,0.129,0.131,0.133,0.134,0.134,0.133,0.132,0.131,0.130,0.129,0.130,0.134,0.132,0.139
2,0.053,0.000,0.000,0.154,0.037,0.084,0.083,0.543,0.540,0.271,0.052,0.280,0.342,0.980,0.038,0.241,0.262,0.389,0.154,0.402,0.056,0.382,0.988,0.138,0.135,0.094,0.093,0.444,0.013,0.179,0.994,0.355,0.372,0.526,0.408,0.003,0.835,0.001,0.039,0.051,0.246,0.443,0.212,0.220,0.239,0.243,0.239,0.067,0.027,0.347,0.243,0.013,0.089,0.066,0.194,0.107,0.124,NaN,0.067,0.037,0.357,0.235,0.006,0.069,0.049,0.159,0.044,0.085,NaN,0.043,0.042,0.041,0.040,0.039,0.038,0.039,0.039,0.040,0.041,0.041,0.041,0.042,0.042,0.043,0.042,0.039,0.039,0.041,0.042,0.049
3,0.079,0.000,0.000,0.182,0.025,0.087,0.053,0.252,0.598,0.317,0.008,0.303,0.289,0.947,0.057,0.390,0.326,0.379,0.213,0.479,0.067,0.434,0.991,0.266,0.255,0.115,0.094,0.365,0.032,0.083,0.981,0.184,0.437,0.659,0.112,0.002,0.876,0.000,0.028,0.055,0.237,0.739,0.115,0.124,0.152,0.120,0.128,0.025,0.181,0.168,0.330,0.000,0.064,0.029,0.221,0.046,0.000,NaN,0.018,0.266,0.175,0.270,0.000,0.037,0.035,0.181,0.016,0.000,NaN,0.058,0.058,0.057,0.056,0.055,0.055,0.055,0.056,0.057,0.058,0.058,0.058,0.058,0.059,0.059,0.058,0.055,0.056,0.058,0.059,0.066
4,0.087,0.000,0.000,0.213,0.027,0.130,0.064,0.015,0.891,0.440,0.024,0.299,0.243,0.971,0.078,0.344,0.233,0.409,0.190,0.438,0.096,0.447,0.993,0.256,0.261,0.129,0.105,0.344,0.026,0.194,0.985,0.180,0.409,0.592,0.119,0.006,0.870,0.002,0.018,0.081,0.135,0.858,0.099,0.114,0.125,0.103,0.108,0.014,0.090,0.187,0.281,0.046,0.094,0.058,0.224,0.122,0.286,NaN,0.009,0.103,0.204,0.270,0.029,0.089,0.069,0.185,0.049,0.195,NaN,0.070,0.070,0.070,0.070,0.069,0.069,0.069,0.069,0.070,0.071,0.071,0.071,0.072,0.072,0.073,0.070,0.069,0.069,0.071,0.072,0.079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,0.872,1.000,1.000,0.284,0.049,0.134,0.143,0.013,0.455,0.376,0.701,0.266,0.305,0.985,0.140,0.306,0.317,0.306,0.261,0.317,0.162,0.421,0.989,0.426,0.416,0.318,0.145,0.391,0.046,0.208,0.995,0.228,0.333,0.475,0.241,0.004,0.766,0.043,0.035,0.119,0.208,0.782,0.237,0.253,0.222,0.232,0.247,0.313,0.086,0.077,0.294,0.042,0.090,0.056,0.127,0.144,0.175,0.006,0.440,0.082,0.132,0.241,0.013,0.056,0.047,0.062,0.044,0.083,0.008,0.094,0.093,0.091,0.090,0.088,0.087,0.087,0.088,0.089,0.091,0.092,0.092,0.092,0.092,0.091,0.093,0.088,0.088,0.092,0.091,0.099
3139,0.885,1.000,1.000,0.875,0.125,0.429,0.257,0.008,0.000,0.291,0.189,0.118,0.367,0.944,0.562,0.217,0.233,0.376,0.544,0.367,0.767,0.329,0.993,0.554,0.541,0.624,0.487,0.312,0.231,0.143,1.000,0.385,0.303,0.395,0.512,0.002,0.640,0.055,0.114,0.791,0.320,0.798,0.101,0.220,0.093,0.184,0.147,0.008,0.153,0.014,0.177,0.071,0.205,0.117,0.112,0.437,0.230,0.009,0.004,0.132,0.008,0.126,0.033,0.316,0.269,0.071,0.245,0.142,0.020,0.603,0.608,0.616,0.620,0.620,0.614,0.607,0.602,0.601,0.608,0.622,0.636,0.645,0.646,0.643,0.609,0.618,0.603,0.622,0.645,0.617
3140,0.914,1.000,1.000,0.282,0.035,0.125,0.070,0.003,0.276,0.538,0.507,0.228,0.456,1.000,0.118,0.317,0.224,0.304,0.199,0.310,0.140,0.408,0.990,0.415,0.358,0.306,0.095,0.384,0.019,0.215,0.990,0.190,0.364,0.347,0.204,0.002,0.792,0.019,0.055,0.117,0.133,0.870,0.202,0.235,0.205,0.211,0.221,0.033,0.120,0.044,0.319,0.274,0.115,0.048,0.273,0.123,0.094,0.008,0.050,0.161,0.047,0.296,0.153,0.097,0.065,0.205,0.050,0.072,0.027,0.101,0.100,0.101,0.101,0.100,0.100,0.100,0.101,0.103,0.105,0.107,0.107,0.106,0.106,0.105,0.101,0.100,0.102,0.106,0.106,0.111
3141,0.945,1.000,1.000,0.394,0.020,0.211,0.126,0.000,NaN,0.619,0.332,0.212,0.314,1.000,0.139,0.225,0.140,0.444,0.160,0.286,0.130,0.447,0.984,0.323,0.275,0.217,0.075,0.381,0.014,0.168,1.000,0.253,0.339,0.359,0.288,0.001,0.813,0.000,0.034,0.111,0.125,0.815,0.217,0.258,0.214,0.215,0.235,0.123,0.075,0.161,0.251,0.088,0.121,0.037,0.297,0.100,0.244,0.000,0.105,0.076,0.193,0.250,0.055,0.091,0.037,0.252,0.036,0.115,0.005,0.082,0.082,0.081,0.080,0.080,0.079,0.079,0.080,0.081,0.083,0.084,0.085,0.085,0.084,0.084,0.082,0.080,0.080,0.084,0.084,0.090
3142,0.959,1.000,1.000,0.317,0.053,0.082,0.077,0.004,0.000,0.542,0.135,0.195,0.416,0.979,0.114,0.244,0.120,0.464,0.205,0.433,0.126,0.434,0.987,0.347,0.277,0.254,0.102,0.348,0.009,0.141,0.992,0.099,0.381,0.523,0.221,0.001,0.673,0.135,0.029,0.119,0.217,0.881,0.142,0.155,0.125,0.131,0.139,0.184,0.000,0.000,0.270,0.077,0.092,0.026,0.148,0.101,0.088,0.026,0.164,0.000,0.000,0.193,0.022,0.089,0.043,0.088,0.031,0.052,0.036,0.077,0.076,0.075,0.074,0.074,0.073,0.073,0.073,0.075,0.077,0.078,0.079,0.078,0.077,0.077,0.076,0.074,0.074,0.078,0.077,0.084

Log Transformed:

,county_name,state,fips,attained_bachelors,attained_doctorate,attained_masters,attained_professional,black,black_homeowners,eight_rooms,electricity_cost,five_rooms,four_rooms,kitchen_complete,lower_quartile_home_value,mean_household_size_owner,mean_household_size_renter,median_age,median_gross_rent,median_gross_rent_frac_income,median_home_value,median_number_rooms,median_year_built,mhhi,mhhi_family,mhhi_nonfamily,more_than_200k,one_person_household,one_room,owners_25_34,plumbing_complete,renter_occupied,seven_rooms,six_rooms,three_rooms,total_pop,transportation_drive_alone,transportation_public,two_rooms,upper_quartile_home_value,vacant_units,white,unemployed_rate_q1_22,unemployed_rate_q2_22,unemployed_rate_q3_22,unemployed_rate_q4_22,unemployed_rate_year_22,emp_location_quotient_natural_resources_and_mining,emp_location_quotient_construction,emp_location_quotient_manufacturing,emp_location_quotient_trade_transportation_and_utilities,emp_location_quotient_information,emp_location_quotient_financial_activities,emp_location_quotient_professional_and_business_services,emp_location_quotient_education_and_health_services,emp_location_quotient_leisure_and_hospitality,emp_location_quotient_other_services,emp_location_quotient_unclassified,wage_location_quotient_natural_resources_and_mining,wage_location_quotient_construction,wage_location_quotient_manufacturing,wage_location_quotient_trade_transportation_and_utilities,wage_location_quotient_information,wage_location_quotient_financial_activities,wage_location_quotient_professional_and_business_services,wage_location_quotient_education_and_health_services,wage_location_quotient_leisure_and_hospitality,wage_location_quotient_other_services,wage_location_quotient_unclassified,house_price_jan_2022,house_price_feb_2022,house_price_mar_2022,house_price_apr_2022,house_price_may_2022,house_price_jun_2022,house_price_july_2022,house_price_aug_2022,house_price_sep_2022,house_price_oct_2022,house_price_nov_2022,house_price_dec_2022,house_price_jan_2023,house_price_feb_2023,house_price_mar_2023,house_price_avg_q1_2022,house_price_avg_q2_2022,house_price_avg_q3_2022,house_price_avg_q4_2022,house_price_avg_q1_2023,house_price_avg_2022
0,4.407,-inf,6.909,-1.806,-4.447,-2.385,-4.325,-1.625,-0.579,-2.259,-4.777,-1.650,-2.161,-0.007,11.423,1.001,0.875,3.651,6.989,3.235,12.013,1.792,7.597,11.045,11.191,10.353,-3.063,-1.344,-4.963,-1.992,-0.005,-1.357,-1.835,-1.446,-3.031,10.972,-0.146,-5.214,-4.629,12.401,-2.346,-0.313,0.903,0.788,0.903,0.710,0.829,0.255,-0.198,0.445,0.077,-2.303,-0.478,-0.821,-0.357,0.336,-0.151,NaN,0.850,-0.094,0.693,0.199,-2.659,-0.821,-0.916,-0.288,0.262,-0.117,NaN,12.223,12.234,12.245,12.258,12.272,12.283,12.290,12.293,12.293,12.294,12.295,12.297,12.302,12.308,12.317,12.234,12.271,12.292,12.295,12.309,12.273
1,4.489,-inf,6.911,-1.580,-4.281,-2.457,-3.969,-2.442,-0.464,-2.327,-4.795,-1.535,-1.892,-0.007,11.927,0.971,0.854,3.770,6.997,3.364,12.331,1.758,7.599,11.072,11.324,10.467,-2.646,-1.233,-4.366,-2.404,-0.003,-1.475,-2.011,-1.528,-3.000,12.333,-0.206,-6.649,-4.426,12.777,-1.259,-0.191,0.956,0.803,0.916,0.742,0.858,-0.223,0.207,-0.580,0.223,-1.309,-0.030,-0.545,-0.151,0.693,-0.105,NaN,-0.073,0.425,-0.478,0.365,-1.772,-0.248,-0.734,0.157,1.022,0.231,NaN,12.685,12.701,12.717,12.733,12.748,12.762,12.770,12.775,12.775,12.776,12.776,12.775,12.775,12.775,12.780,12.701,12.748,12.773,12.776,12.777,12.750
2,4.605,-inf,6.913,-2.698,-5.088,-3.544,-4.698,-0.750,-0.616,-2.816,-4.255,-1.452,-1.791,-0.006,10.692,0.908,0.880,3.694,6.405,3.254,11.402,1.668,7.591,10.503,10.795,9.938,-3.414,-1.109,-5.651,-2.296,-0.002,-0.973,-2.105,-1.645,-2.141,10.137,-0.185,-7.097,-3.871,12.023,-1.509,-0.807,1.466,1.262,1.427,1.435,1.401,1.058,-0.942,1.176,-0.117,-2.408,-0.755,-0.892,-0.446,-0.117,-0.616,NaN,1.435,-0.616,1.138,0.077,-2.996,-1.139,-1.427,-0.301,-0.163,-0.386,NaN,11.703,11.703,11.699,11.698,11.701,11.711,11.721,11.731,11.731,11.728,11.722,11.721,11.740,11.763,11.788,11.702,11.704,11.728,11.724,11.764,11.714
3,5.004,-inf,6.915,-2.532,-5.464,-3.518,-5.151,-1.519,-0.514,-2.659,-6.157,-1.395,-1.919,-0.016,11.005,1.109,0.993,3.681,6.612,3.371,11.542,1.740,7.593,10.902,11.127,10.023,-3.410,-1.305,-4.737,-3.059,-0.007,-1.550,-1.946,-1.421,-3.437,10.017,-0.140,-inf,-4.224,12.067,-1.541,-0.300,0.981,0.833,1.030,0.818,0.920,0.077,0.963,0.451,0.191,-inf,-1.079,-1.715,-0.315,-0.968,-inf,NaN,0.095,1.356,0.425,0.215,-inf,-1.772,-1.772,-0.174,-1.171,-inf,NaN,11.956,11.969,11.979,11.985,11.991,12.004,12.016,12.024,12.022,12.019,12.015,12.012,12.026,12.043,12.063,11.968,11.993,12.021,12.015,12.044,12.000
4,5.100,-inf,6.917,-2.375,-5.420,-3.111,-4.957,-4.369,-0.116,-2.332,-5.032,-1.403,-2.048,-0.009,11.280,1.051,0.824,3.716,6.538,3.311,11.836,1.758,7.595,10.875,11.141,10.078,-3.293,-1.365,-4.926,-2.213,-0.006,-1.569,-2.012,-1.527,-3.377,10.983,-0.146,-6.681,-4.661,12.314,-2.028,-0.152,0.875,0.773,0.861,0.693,0.803,-0.478,0.262,0.560,0.030,-1.139,-0.693,-1.022,-0.301,0.010,0.215,NaN,-0.528,0.405,0.577,0.215,-1.470,-0.892,-1.079,-0.151,-0.062,0.445,NaN,12.123,12.138,12.156,12.173,12.187,12.197,12.202,12.204,12.203,12.202,12.199,12.196,12.208,12.225,12.245,12.139,12.186,12.203,12.199,12.226,12.182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,7.401,3.912,10.934,-2.087,-4.813,-3.079,-4.156,-4.485,-0.788,-2.489,-1.652,-1.486,-1.878,-0.004,11.806,1.001,0.978,3.595,6.756,3.105,12.289,1.723,7.591,11.247,11.449,10.614,-2.973,-1.238,-4.360,-2.147,-0.002,-1.366,-2.218,-1.749,-2.668,10.656,-0.264,-3.725,-4.001,12.601,-1.660,-0.245,1.562,1.378,1.361,1.395,1.427,2.603,0.223,-0.329,0.077,-1.238,-0.734,-1.050,-0.868,0.174,-0.274,-1.897,3.314,0.174,0.140,0.104,-2.303,-1.347,-1.470,-1.238,-0.163,-0.416,-1.833,12.381,12.387,12.394,12.400,12.404,12.408,12.412,12.417,12.419,12.422,12.424,12.427,12.430,12.437,12.446,12.388,12.404,12.416,12.424,12.438,12.408
3139,7.416,3.912,10.934,-0.961,-3.868,-1.917,-3.572,-4.945,-inf,-2.747,-2.962,-1.977,-1.736,-0.016,13.139,0.871,0.824,3.679,7.329,3.195,13.759,1.589,7.595,11.456,11.642,11.128,-1.759,-1.465,-2.748,-2.520,0.000,-0.900,-2.311,-1.932,-1.914,10.057,-0.429,-3.481,-2.808,14.283,-1.270,-0.224,0.889,1.262,0.624,1.184,1.021,-1.109,0.793,-2.040,-0.431,-0.713,0.086,-0.315,-0.994,1.286,0.000,-1.561,-1.273,0.652,-2.659,-0.545,-1.347,0.378,0.278,-1.109,1.556,0.131,-0.916,14.161,14.186,14.215,14.242,14.263,14.273,14.269,14.258,14.242,14.242,14.259,14.284,14.304,14.310,14.313,14.187,14.259,14.257,14.262,14.309,14.242
3140,7.447,3.912,10.934,-2.094,-5.134,-3.150,-4.875,-5.978,-1.288,-2.132,-1.975,-1.592,-1.558,0.000,11.649,1.015,0.806,3.592,6.567,3.091,12.160,1.705,7.592,11.227,11.345,10.587,-3.393,-1.256,-5.235,-2.112,-0.004,-1.522,-2.128,-2.062,-2.835,9.929,-0.233,-4.535,-3.539,12.588,-2.042,-0.139,1.427,1.317,1.290,1.308,1.337,0.358,0.548,-0.892,0.157,0.637,-0.494,-1.204,-0.105,0.020,-0.892,-1.661,1.147,0.854,-0.892,0.307,0.182,-0.799,-1.139,-0.051,-0.041,-0.545,-0.635,12.443,12.461,12.483,12.502,12.518,12.533,12.543,12.550,12.554,12.557,12.562,12.564,12.563,12.568,12.578,12.462,12.518,12.549,12.561,12.570,12.523
3141,7.481,3.912,10.934,-1.758,-5.708,-2.630,-4.281,-8.958,NaN,-1.990,-2.399,-1.639,-1.857,0.000,11.803,0.884,0.621,3.754,6.431,3.045,12.093,1.758,7.587,11.039,11.174,10.362,-3.634,-1.264,-5.546,-2.362,0.000,-1.276,-2.199,-2.029,-2.489,8.958,-0.210,-inf,-4.020,12.548,-2.097,-0.203,1.489,1.395,1.326,1.326,1.386,1.670,0.077,0.405,-0.083,-0.494,-0.446,-1.470,-0.020,-0.186,0.058,-inf,1.879,0.104,0.525,0.140,-0.844,-0.868,-1.715,0.157,-0.357,-0.083,-2.408,12.261,12.274,12.286,12.298,12.310,12.321,12.329,12.335,12.336,12.341,12.346,12.352,12.356,12.363,12.373,12.274,12.310,12.334,12.346,12.364,12.316
3142,7.496,3.912,10.934,-1.976,-4.734,-3.568,-4.782,-5.619,-inf,-2.124,-3.296,-1.692,-1.633,-0.006,11.615,0.912,0.571,3.775,6.588,3.303,12.070,1.740,7.589,11.091,11.178,10.462,-3.326,-1.354,-5.943,-2.535,-0.003,-2.040,-2.081,-1.651,-2.756,8.838,-0.383,-2.584,-4.170,12.603,-1.623,-0.126,1.142,0.993,0.861,0.889,0.978,2.073,-inf,-inf,-0.010,-0.635,-0.713,-1.833,-0.713,-0.174,-0.968,-0.431,2.323,-inf,-inf,-0.117,-1.772,-0.892,-1.561,-0.892,-0.511,-0.868,-0.342,12.203,12.212,12.222,12.231,12.241,12.249,12.254,12.258,12.263,12.272,12.281,12.284,12.280,12.284,12.296,12.212,12.240,12.258,12.279,12.287,12.248

# Redfin Data

In [7]:
pd.set_option('display.max_columns', None)


redfin = pd.read_csv(github+'redfin.csv').drop(columns = ['Unnamed: 0','period_begin','region_type',
                                                          'is_seasonally_adjusted','last_updated','city',
                                                          'period_duration'])

# output data
print('Raw Data:')             
display(redfin)               

# Label Encoding
redfin_strings = redfin.select_dtypes(include=['object'])
redfin_string_encoded = label_encode(redfin_strings)
redfin_encoded = redfin_string_encoded.join(redfin.select_dtypes(exclude=['object']))

print('Standard Scaling:')
display(scale_set(redfin_encoded)[0]) 
print('Min-Max Scaling:')
display(scale_set(redfin_encoded)[1])
print('Log Transformed:')
display(log_transform(redfin_encoded))

# output files to excel
scale_set(redfin_encoded)[0].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\redfin\redfin_standard_scaled.csv')
scale_set(redfin_encoded)[1].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\redfin\redfin_minmax_scaled.csv')
log_transform(redfin_encoded).round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\redfin\redfin_log_transformed.csv')
redfin_encoded.round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\redfin\redfin_label_encoded.csv')

scale_set(log_transform(redfin_encoded).replace([np.inf, -np.inf], 0))[0].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\redfin\redfin_log_ss.csv')
scale_set(log_transform(redfin_encoded).replace([np.inf, -np.inf], 0))[1].round(6).to_csv(r'C:\Users\Mattl\Desktop\Data\redfin\redfin_log_mm.csv')

Raw Data:

,period_end,region_type_id,table_id,region,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code
0,2017-12-31,5,396,"Larimer County, CO",Colorado,CO,Multi-Family (2-4 Unit),4,465000.000,-0.016,-0.065,359900.000,0.000,0.043,194.097,0.140,0.003,180.000,0.075,0.124,7.000,0.750,0.167,2.000,-0.667,-0.500,1.000,-0.857,-0.500,7.000,-0.222,-0.125,1.000,-1.300,-0.300,29.000,-31.000,-44.000,0.978,-0.013,-0.003,0.143,-0.107,-0.190,NaN,NaN,NaN,0.000,-0.333,0.000,"Fort Collins, CO",22660.000
1,2016-12-31,5,2932,"Orleans County, VT",Vermont,VT,Single Family Residential,6,130100.000,-0.192,0.308,154700.000,-0.139,-0.111,89.583,-0.257,0.212,88.794,-0.131,-0.135,17.000,-0.292,-0.150,3.000,-0.625,-0.667,18.000,-0.250,-0.400,281.000,-0.082,-0.281,16.500,3.700,-3.100,260.000,38.000,54.000,0.915,-0.040,-0.008,0.059,-0.066,-0.041,0.068,-0.037,0.019,0.000,0.000,-0.222,Vermont nonmetropolitan area,NaN
2,2020-12-31,5,1396,"Mackinac County, MI",Michigan,MI,Single Family Residential,6,125000.000,NaN,-0.628,45000.000,NaN,-0.438,115.207,NaN,-0.075,31.780,NaN,-0.583,1.000,NaN,0.000,NaN,NaN,NaN,1.000,NaN,0.000,6.000,NaN,-0.143,6.000,NaN,-1.000,95.000,NaN,-227.000,0.927,NaN,-0.048,0.000,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,Michigan nonmetropolitan area,NaN
3,2019-12-31,5,888,"Starke County, IN",Indiana,IN,Single Family Residential,6,124900.000,0.243,0.315,97400.000,0.147,0.207,81.468,-0.023,0.305,58.958,-0.113,0.027,27.000,0.227,0.227,12.000,0.333,0.000,9.000,-0.571,-0.471,120.000,-0.149,0.091,4.400,-2.000,-0.600,143.000,31.000,62.000,0.961,0.045,-0.003,0.185,0.003,0.140,NaN,NaN,NaN,0.083,0.083,0.083,Indiana nonmetropolitan area,NaN
4,2019-12-31,5,1012,"Butler County, KS",Kansas,KS,Multi-Family (2-4 Unit),4,367000.000,3.587,1.802,100000.000,-0.365,NaN,201.206,5.389,3.129,67.995,-0.189,NaN,1.000,-0.667,0.000,1.000,-0.667,NaN,3.000,2.000,NaN,13.000,0.182,3.333,13.000,9.300,10.000,35.000,10.000,-245.000,1.006,0.062,0.070,1.000,1.000,1.000,NaN,NaN,NaN,0.000,0.000,NaN,"Wichita, KS",48620.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48844,2018-12-31,5,983,"Pottawattamie County, IA",Iowa,IA,All Residential,-1,160000.000,0.231,0.981,148000.000,-0.013,-0.168,103.009,0.055,0.592,100.141,0.021,-0.026,67.000,1.161,3.188,40.000,1.000,2.636,52.000,-0.257,2.059,297.000,-0.033,6.244,4.400,-5.500,1.800,67.000,19.000,-7.000,0.981,-0.009,0.003,0.224,-0.034,0.099,0.017,-0.035,-0.130,0.025,-0.175,-0.248,"Omaha, NE",36540.000
48845,2016-12-31,5,1124,"Bullitt County, KY",Kentucky,KY,Single Family Residential,6,166965.500,-0.017,0.044,166750.000,0.011,-0.013,108.754,0.050,0.091,111.579,0.016,0.082,88.000,-0.022,0.048,51.000,-0.215,0.308,67.000,-0.230,0.015,260.000,-0.041,-0.051,3.000,0.000,-0.300,39.000,5.000,6.000,0.973,-0.008,-0.006,0.080,-0.054,-0.051,0.058,-0.075,-0.008,0.333,-0.036,0.051,"Louisville, KY",31140.000
48846,2016-12-31,5,1246,"East Baton Rouge Parish, LA",Louisiana,LA,All Residential,-1,167550.000,-0.043,-0.127,169900.000,-0.051,-0.029,98.119,-0.074,-0.106,106.332,-0.025,0.013,494.000,-0.050,0.133,325.000,-0.069,0.451,NaN,NaN,NaN,NaN,NaN,NaN,3.200,0.000,-1.200,35.000,-1.000,-48.000,0.952,-0.006,-0.019,0.113,-0.000,0.010,0.118,-0.039,0.004,0.434,-0.036,0.126,"Baton Rouge, LA",12940.000
48847,2016-12-31,5,1246,"East Baton Rouge Parish, LA",Louisiana,LA,Townhouse,13,105000.000,-0.160,-0.234,169900.000,-0.051,-0.029,75.132,-0.291,-0.297,106.332,-0.025,0.013,34.000,0.478,0.259,22.000,1.200,0.467,NaN,NaN,NaN,NaN,NaN,NaN,2.600,-1.300,-2.300,35.000,-35.000,-43.000,0.886,-0.083,-0.099,0.059,-0.028,-0.126,0.090,0.022,0.014,0.364,0.064,0.230,"Baton Rouge, LA",12940.000
48848,2021-12-31,5,2433,"Abbeville County, SC",South Carolina,SC,All Residential,-1,205000.000,0.085,0.318,172311.000,-0.317,0.352,124.544,0.059,0.549,121.929,-0.128,0.434,25.000,0.471,0.786,13.000,-0.133,1.600,10.000,-0.444,-0.167,35.000,-0.239,-0.125,1.400,-1.300,-1.500,52.000,-19.000,-57.000,0.965,0.003,0.024,0.280,0.221,0.209,0.086,-0.023,NaN,0.000,-0.067,-0.200,South Carolina nonmetropolitan area,NaN

Standard Scaling:

,period_end,region,state,state_code,property_type,parent_metro_region,region_type_id,table_id,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region_metro_code
0,-1.119,0.015,-1.464,-1.463,0.176,-0.762,0.000,-1.368,0.059,0.766,-0.008,-0.241,0.594,-0.067,-0.177,0.104,-0.007,-0.039,0.263,0.004,-0.016,-0.303,0.571,-0.060,-0.314,-0.634,-0.236,-0.327,-1.089,-0.354,-0.317,-0.548,-0.174,-0.333,-0.110,0.026,-0.331,-0.189,-0.152,0.299,-0.219,-0.108,-0.154,-0.490,-0.949,NaN,NaN,NaN,-0.868,-1.443,-0.080,-0.644
1,-1.626,0.637,1.318,1.426,0.865,1.423,0.000,1.387,0.535,-0.328,-0.010,0.080,-0.458,-0.278,-0.390,-0.088,-0.011,-0.005,-0.415,-0.054,-0.069,-0.269,-0.434,-0.115,-0.309,-0.597,-0.275,-0.247,-0.189,-0.310,0.043,0.123,-0.275,1.136,0.585,-0.195,0.862,0.194,0.299,-0.926,-0.725,-0.198,-0.586,-0.288,-0.247,-0.804,0.128,0.086,-0.868,0.058,-0.999,NaN
2,0.401,0.185,-0.252,-0.235,0.865,0.186,0.000,-0.281,0.535,-0.345,NaN,-0.726,-1.021,NaN,-0.840,-0.041,NaN,-0.051,-0.839,NaN,-0.160,-0.324,NaN,-0.089,NaN,NaN,NaN,-0.327,NaN,-0.133,-0.319,NaN,-0.186,0.141,NaN,-0.029,0.010,NaN,-0.995,-0.709,NaN,-0.916,-0.889,NaN,-0.053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.105,1.217,-0.822,-0.741,0.865,-0.381,0.000,-0.833,0.535,-0.345,-0.005,0.087,-0.752,0.155,0.048,-0.103,-0.009,0.010,-0.637,-0.049,-0.036,-0.234,0.067,-0.050,-0.267,0.266,-0.117,-0.289,-0.665,-0.341,-0.168,-0.198,-0.034,-0.011,-0.208,0.002,0.258,0.155,0.336,-0.028,0.897,-0.108,0.064,0.057,0.604,NaN,NaN,NaN,-0.514,0.433,0.265,NaN
4,-0.105,-1.380,-0.680,-0.669,0.176,1.586,0.000,-0.699,0.059,0.446,0.031,1.367,-0.738,-0.619,NaN,0.117,0.041,0.465,-0.570,-0.071,NaN,-0.324,-0.795,-0.089,-0.319,-0.634,NaN,-0.317,3.147,NaN,-0.309,1.380,2.062,0.805,1.364,0.839,-0.300,0.039,-1.077,0.836,1.226,1.233,4.261,4.989,4.651,NaN,NaN,NaN,-0.868,0.058,NaN,1.620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48844,-0.612,0.828,-0.751,-0.958,-1.201,0.527,0.000,-0.730,-1.133,-0.230,-0.005,0.661,-0.492,-0.087,-0.469,-0.064,-0.008,0.056,-0.331,-0.011,-0.047,-0.094,0.968,0.462,-0.134,0.867,0.511,-0.088,-0.199,0.778,0.064,0.357,3.944,-0.011,-0.694,0.192,-0.135,0.089,0.018,0.355,-0.145,0.006,0.264,-0.129,0.412,-1.247,0.145,-1.505,-0.761,-0.730,-1.105,0.567
48845,-1.626,-1.398,-0.608,-0.597,0.865,-0.007,0.000,-0.577,0.535,-0.207,-0.008,-0.147,-0.396,-0.050,-0.255,-0.053,-0.008,-0.024,-0.246,-0.013,-0.025,-0.021,-0.174,-0.081,-0.083,-0.228,-0.043,-0.018,-0.159,-0.126,0.016,0.319,-0.126,-0.143,0.070,0.026,-0.279,0.011,0.078,0.190,-0.109,-0.162,-0.480,-0.226,-0.295,-0.891,-0.276,-0.203,0.548,-0.103,0.132,0.096
48846,-1.626,-0.812,-0.537,-0.524,-1.201,-1.562,0.000,-0.444,-1.133,-0.206,-0.008,-0.295,-0.380,-0.144,-0.277,-0.073,-0.009,-0.056,-0.285,-0.024,-0.039,1.394,-0.201,-0.066,1.212,-0.096,-0.009,NaN,NaN,NaN,NaN,NaN,NaN,-0.124,0.070,-0.045,-0.300,-0.022,-0.170,-0.206,-0.075,-0.387,-0.306,0.039,-0.005,-0.366,0.110,-0.079,0.975,-0.104,0.440,-1.491
48847,-1.626,-0.812,-0.537,-0.524,1.553,-1.562,0.000,-0.444,2.203,-0.410,-0.010,-0.386,-0.380,-0.144,-0.277,-0.115,-0.011,-0.087,-0.285,-0.024,-0.039,-0.209,0.309,-0.044,-0.219,1.047,-0.006,NaN,NaN,NaN,NaN,NaN,NaN,-0.181,-0.110,-0.132,-0.300,-0.211,-0.147,-1.506,-1.551,-1.854,-0.586,-0.099,-0.648,-0.610,0.755,0.028,0.677,0.345,0.873,-1.491
48848,0.908,-1.732,0.961,0.992,-1.201,1.131,0.000,0.845,-1.133,-0.083,-0.007,0.089,-0.368,-0.547,0.248,-0.024,-0.008,0.049,-0.169,-0.053,0.047,-0.241,0.302,0.047,-0.262,-0.154,0.264,-0.285,-0.477,-0.207,-0.280,-0.628,-0.174,-0.295,-0.110,-0.069,-0.212,-0.122,-0.212,0.045,0.090,0.396,0.553,1.135,0.928,-0.646,0.275,NaN,-0.868,-0.242,-0.907,NaN

Min-Max Scaling:

,period_end,region,state,state_code,property_type,parent_metro_region,region_type_id,table_id,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region_metro_code
0,0.167,0.506,0.104,0.104,0.500,0.301,0.000,0.122,0.357,0.013,0.000,0.006,0.058,0.018,0.031,0.003,0.000,0.001,0.016,0.002,0.003,0.001,0.028,0.003,0.000,0.003,0.001,0.000,0.003,0.003,0.000,0.066,0.010,0.001,0.533,0.638,0.003,0.448,0.478,0.383,0.558,0.512,0.143,0.446,0.405,NaN,NaN,NaN,0.000,0.333,0.500,0.316
1,0.000,0.686,0.917,0.938,0.750,0.927,0.000,0.907,0.500,0.004,0.000,0.009,0.024,0.015,0.027,0.001,0.000,0.001,0.008,0.002,0.002,0.002,0.011,0.002,0.000,0.004,0.001,0.003,0.024,0.004,0.015,0.079,0.009,0.019,0.540,0.636,0.031,0.452,0.484,0.332,0.543,0.508,0.059,0.467,0.479,0.068,0.468,0.494,0.000,0.500,0.389,NaN
2,0.667,0.555,0.458,0.458,0.750,0.573,0.000,0.431,0.500,0.003,NaN,0.002,0.006,NaN,0.017,0.001,NaN,0.001,0.003,NaN,0.001,0.000,NaN,0.002,NaN,NaN,NaN,0.000,NaN,0.006,0.000,NaN,0.010,0.007,NaN,0.638,0.011,NaN,0.466,0.341,NaN,0.481,0.000,NaN,0.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.500,0.854,0.292,0.312,0.750,0.410,0.000,0.274,0.500,0.003,0.000,0.009,0.015,0.021,0.036,0.001,0.000,0.002,0.005,0.002,0.002,0.003,0.019,0.003,0.002,0.015,0.003,0.001,0.013,0.003,0.006,0.073,0.013,0.005,0.532,0.638,0.017,0.452,0.485,0.369,0.592,0.512,0.185,0.502,0.570,NaN,NaN,NaN,0.083,0.542,0.542,NaN
4,0.500,0.102,0.333,0.333,0.500,0.973,0.000,0.312,0.357,0.010,0.000,0.019,0.015,0.011,NaN,0.003,0.000,0.005,0.006,0.002,NaN,0.000,0.005,0.002,0.000,0.003,NaN,0.000,0.099,NaN,0.001,0.104,0.053,0.015,0.548,0.646,0.004,0.450,0.465,0.405,0.602,0.562,1.000,1.000,1.000,NaN,NaN,NaN,0.000,0.500,NaN,0.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48844,0.333,0.742,0.312,0.250,0.000,0.670,0.000,0.304,0.000,0.004,0.000,0.013,0.023,0.018,0.025,0.001,0.000,0.002,0.009,0.002,0.002,0.008,0.035,0.009,0.006,0.022,0.010,0.009,0.023,0.020,0.016,0.084,0.089,0.005,0.527,0.640,0.008,0.451,0.481,0.385,0.561,0.516,0.224,0.483,0.549,0.017,0.469,0.414,0.025,0.412,0.376,0.666
48845,0.000,0.097,0.354,0.354,0.750,0.517,0.000,0.347,0.500,0.005,0.000,0.007,0.026,0.018,0.030,0.001,0.000,0.001,0.010,0.002,0.002,0.010,0.015,0.002,0.007,0.008,0.004,0.012,0.024,0.006,0.014,0.083,0.011,0.004,0.535,0.638,0.005,0.450,0.481,0.378,0.562,0.510,0.080,0.473,0.474,0.058,0.446,0.480,0.333,0.482,0.526,0.530
48846,0.000,0.267,0.375,0.375,0.000,0.072,0.000,0.385,0.000,0.005,0.000,0.006,0.027,0.017,0.029,0.001,0.000,0.001,0.010,0.002,0.002,0.059,0.015,0.002,0.048,0.010,0.004,NaN,NaN,NaN,NaN,NaN,NaN,0.004,0.535,0.638,0.004,0.450,0.478,0.362,0.563,0.501,0.113,0.500,0.505,0.118,0.467,0.486,0.434,0.482,0.563,0.072
48847,0.000,0.267,0.375,0.375,1.000,0.072,0.000,0.385,1.000,0.003,0.000,0.005,0.027,0.017,0.029,0.001,0.000,0.001,0.010,0.002,0.002,0.004,0.024,0.003,0.003,0.025,0.004,NaN,NaN,NaN,NaN,NaN,NaN,0.003,0.533,0.637,0.004,0.447,0.478,0.309,0.519,0.446,0.059,0.486,0.437,0.090,0.501,0.491,0.364,0.532,0.615,0.072
48848,0.833,0.000,0.812,0.812,0.000,0.843,0.000,0.752,0.000,0.006,0.000,0.009,0.027,0.012,0.041,0.002,0.000,0.002,0.011,0.002,0.003,0.003,0.023,0.004,0.002,0.009,0.007,0.002,0.017,0.005,0.002,0.064,0.010,0.002,0.533,0.638,0.006,0.448,0.477,0.372,0.568,0.531,0.280,0.611,0.604,0.086,0.476,NaN,0.000,0.467,0.400,NaN

Log Transformed:

,period_end,region,state,state_code,property_type,parent_metro_region,region_type_id,table_id,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region_metro_code
0,0.000,7.249,1.609,1.609,0.693,5.649,1.609,5.981,1.386,13.050,NaN,NaN,12.794,-inf,-3.142,5.268,-1.967,-5.903,5.193,-2.584,-2.088,1.946,-0.288,-1.792,0.693,NaN,NaN,0.000,NaN,NaN,1.946,NaN,NaN,0.000,NaN,NaN,3.367,NaN,NaN,-0.022,NaN,NaN,-1.946,NaN,NaN,NaN,NaN,NaN,-inf,NaN,-inf,10.028
1,-inf,7.554,3.784,3.807,1.099,6.773,1.609,7.983,1.792,11.776,NaN,-1.179,11.949,NaN,NaN,4.495,NaN,-1.549,4.486,NaN,NaN,2.833,NaN,NaN,1.099,NaN,NaN,2.890,NaN,NaN,5.638,NaN,NaN,2.803,1.308,NaN,5.561,3.638,3.989,-0.088,NaN,NaN,-2.833,NaN,NaN,-2.694,NaN,-3.962,-inf,-inf,NaN,NaN
2,1.386,7.342,3.091,3.091,1.099,6.292,1.609,7.241,1.792,11.736,NaN,NaN,10.714,NaN,NaN,4.747,NaN,NaN,3.459,NaN,NaN,0.000,NaN,-inf,NaN,NaN,NaN,0.000,NaN,-inf,1.792,NaN,NaN,1.792,NaN,NaN,4.554,NaN,NaN,-0.076,NaN,NaN,-inf,NaN,-inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.099,7.773,2.639,2.708,1.099,5.958,1.609,6.789,1.792,11.735,-1.416,-1.154,11.487,-1.916,-1.575,4.400,NaN,-1.187,4.077,NaN,-3.605,3.296,-1.482,-1.482,2.485,-1.099,-inf,2.197,NaN,NaN,4.787,NaN,-2.398,1.482,NaN,NaN,4.963,3.434,4.127,-0.039,-3.100,NaN,-1.686,-5.694,-1.968,NaN,NaN,NaN,-2.485,-2.485,-2.485,NaN
4,1.099,5.645,2.773,2.773,0.693,6.822,1.609,6.920,1.386,12.813,1.277,0.589,11.513,NaN,NaN,5.304,1.684,1.141,4.219,NaN,NaN,0.000,NaN,-inf,0.000,NaN,NaN,1.099,0.693,NaN,2.565,-1.705,1.204,2.565,2.230,2.303,3.555,2.303,NaN,0.006,-2.776,-2.659,0.000,0.000,0.000,NaN,NaN,NaN,-inf,-inf,NaN,10.792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48844,0.693,7.631,2.708,2.485,-inf,6.449,1.609,6.891,NaN,11.983,-1.466,-0.019,11.905,NaN,NaN,4.635,-2.900,-0.524,4.607,-3.873,NaN,4.205,0.150,1.159,3.689,0.000,0.969,3.951,NaN,0.722,5.694,NaN,1.832,1.482,NaN,0.588,4.205,2.944,NaN,-0.019,NaN,-5.863,-1.497,NaN,-2.314,-4.084,NaN,NaN,-3.689,NaN,NaN,10.506
48845,-inf,5.595,2.833,2.833,1.099,6.190,1.609,7.025,1.792,12.026,NaN,-3.127,12.024,-4.490,NaN,4.689,-2.995,-2.401,4.715,-4.133,-2.503,4.477,NaN,-3.045,3.932,NaN,-1.179,4.205,NaN,-4.190,5.561,NaN,NaN,1.099,-inf,NaN,3.664,1.609,1.792,-0.028,NaN,NaN,-2.531,NaN,NaN,-2.853,NaN,NaN,-1.099,NaN,-2.970,10.346
48846,-inf,6.608,2.890,2.890,-inf,4.220,1.609,7.128,NaN,12.029,NaN,NaN,12.043,NaN,NaN,4.586,NaN,NaN,4.667,NaN,-4.367,6.203,NaN,-2.017,5.784,NaN,-0.797,NaN,NaN,NaN,NaN,NaN,NaN,1.163,-inf,NaN,3.555,NaN,NaN,-0.049,NaN,NaN,-2.177,NaN,-4.590,-2.139,NaN,-5.630,-0.835,NaN,-2.073,9.468
48847,-inf,6.608,2.890,2.890,1.386,4.220,1.609,7.128,2.565,11.562,NaN,NaN,12.043,NaN,NaN,4.319,NaN,NaN,4.667,NaN,-4.367,3.526,-0.738,-1.350,3.091,0.182,-0.762,NaN,NaN,NaN,NaN,NaN,NaN,0.956,NaN,NaN,3.555,NaN,NaN,-0.121,NaN,NaN,-2.833,NaN,NaN,-2.409,-3.795,-4.301,-1.012,-2.755,-1.468,9.468
48848,1.609,-inf,3.664,3.664,-inf,6.678,1.609,7.797,NaN,12.231,-2.469,-1.145,12.057,NaN,-1.044,4.825,-2.827,-0.599,4.803,NaN,-0.835,3.219,-0.754,-0.241,2.565,NaN,0.470,2.303,NaN,NaN,3.555,NaN,NaN,0.336,NaN,NaN,3.951,NaN,NaN,-0.035,-5.863,-3.720,-1.273,-1.509,-1.567,-2.457,NaN,NaN,-inf,NaN,NaN,NaN

# FHFA

In [37]:
fhfa = pd.read_csv(github_r+'fhfa_raw.csv')
# limit to 2016--> 2022 year end
fhfa = fhfa[(fhfa['year'].isin([2016,2017,2018,2019,2020,2021,2022])) & (fhfa['qtr'] == 4)]
# pivot on divisons
# fhfa_u = fhfa.pivot(index='year', columns='division', values='index_po_seasonally_adjusted').reset_index()
# fhfa_u.to_csv(r'C:\Users\Mattl\Desktop\Data\fhfa\fhfa.csv')
# display(fhfa_u)

division,year,DV_ENC,DV_ESC,DV_MA,DV_MT,DV_NE,DV_PAC,DV_SA,DV_WNC,DV_WSC,USA
0,2016,192.240,211.780,213.610,300.220,218.140,265.280,231.830,232.140,247.360,231.200
1,2017,203.110,223.240,223.640,325.960,229.720,287.200,246.110,244.120,262.230,245.570
2,2018,214.770,236.590,234.140,352.210,240.650,303.020,260.860,257.810,273.900,259.390
3,2019,226.780,250.070,245.440,378.050,252.270,318.660,276.930,271.310,286.210,273.680
4,2020,252.040,277.790,273.370,429.860,285.020,357.140,308.010,298.590,312.500,304.480
5,2021,288.270,330.800,312.050,530.630,332.390,426.870,371.630,339.990,369.350,358.910
6,2022,311.780,365.480,338.330,563.190,358.770,439.430,417.610,366.700,403.870,389.080

# FRED

In [6]:
fred       = pd.read_csv(github_r+'fred_raw.csv')
fred       = fred[(fred['DATE'] >= '2016-12-31') & (fred['DATE'] < '2023-01-01')]
fred['yr-mo'] = pd.DatetimeIndex(fred['DATE']).year.astype(str) + '-' + pd.DatetimeIndex(fred['DATE']).month.astype(str) 
fred = fred.sort_values('DATE',ascending=False).groupby('yr-mo').head(1)
fred = fred[pd.DatetimeIndex(fred['DATE']).month == 12] 
fred.to_csv(r'C:\Users\Mattl\Desktop\Data\fred.csv')
fred

            DATE  MORTGAGE30US    yr-mo
2700  2022-12-29         6.420  2022-12
2648  2021-12-30         3.110  2021-12
2596  2020-12-31         2.670  2020-12
2543  2019-12-26         3.740  2019-12
2491  2018-12-27         4.550  2018-12
2439  2017-12-28         3.990  2017-12

# Census Data

In [13]:
census = pd.read_csv(github+'census.csv').drop(columns = 'NAME')
print('Raw Data:')             
display(census)               

# Label Encoding
census_strings = census.select_dtypes(include=['object'])
census_string_encoded = label_encode(census_strings)
census_encoded = census_string_encoded.join(census.select_dtypes(exclude=['object']))
display(census_encoded)

print('Standard Scaling:')
display(scale_set(census_encoded)[0]) 
print('Min-Max Scaling:')
display(scale_set(census_encoded)[1])
print('Log Transformed:')
display(log_transform(census_encoded))
print('Log Transformed - SS:')
display(scale_set(log_transform(census_encoded).replace([np.inf, -np.inf], 0))[0])
print('Log Transformed - MM:')
display(scale_set(log_transform(census_encoded).replace([np.inf, -np.inf], 0))[1])

# output files to excel
scale_set(census)[0].to_csv(r'C:\Users\Mattl\Desktop\Data\census\census_standard_scaled.csv')
scale_set(census)[1].to_csv(r'C:\Users\Mattl\Desktop\Data\census\census_minmax_scaled.csv')
log_transform(census).to_csv(r'C:\Users\Mattl\Desktop\Data\census\census_log_transformed.csv')
census_encoded.to_csv(r'C:\Users\Mattl\Desktop\Data\census\census_label_encoded.csv')
scale_set(log_transform(census_encoded).replace([np.inf, -np.inf], 0))[0].to_csv(r'C:\Users\Mattl\Desktop\Data\census\census_log_ss.csv')
scale_set(log_transform(census_encoded).replace([np.inf, -np.inf], 0))[1].to_csv(r'C:\Users\Mattl\Desktop\Data\census\census_log_mm.csv')

Raw Data:

,GEOID,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,vacant_units,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,20161,2.480,28264,85,8595,1379,53296.000,76786.000,37950.000,3979,...,5.300,968.000,1984,26554,26523,31.500,146900.000,211500.000,286400.000,2167
1,19159,2.540,1606,7,585,79,57700.000,76250.000,30345.000,809,...,6.200,639.000,1962,1847,1840,29.500,63800.000,111300.000,217600.000,14
2,30009,2.370,3575,19,1547,269,63178.000,82083.000,34108.000,1865,...,5.400,841.000,1981,4500,4494,24.400,187800.000,297500.000,477300.000,367
3,16007,2.960,1927,17,521,81,60337.000,75882.000,25673.000,1637,...,6.400,598.000,1971,2223,2230,26.400,97200.000,160200.000,270600.000,478
4,55011,2.490,5401,7,1650,136,61167.000,75954.000,35044.000,992,...,6.200,730.000,1971,5505,5505,25.200,106800.000,164500.000,245300.000,138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,53003,2.330,7477,53,2821,499,57263.000,73972.000,37745.000,752,...,6.000,856.000,1976,9278,9255,28.700,155000.000,229300.000,323700.000,865
3217,13043,2.960,3650,0,1288,74,36763.000,47221.000,18268.000,602,...,5.300,653.000,1990,4034,4015,28.000,45000.000,94700.000,203900.000,176
3218,48451,2.620,44500,132,13372,1745,62052.000,76060.000,35420.000,6226,...,5.200,917.000,1977,44554,44344,28.000,89800.000,156600.000,230400.000,2073
3219,39089,2.700,67038,143,15584,4999,72771.000,88792.000,39470.000,6090,...,6.200,894.000,1978,66081,65809,26.300,129500.000,195100.000,284300.000,3439
3220,19193,2.640,43104,564,11034,1643,63061.000,76827.000,34683.000,2825,...,5.900,838.000,1957,39563,39362,25.900,89700.000,139600.000,206500.000,2104

,GEOID,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,vacant_units,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,20161,2.480,28264,85,8595,1379,53296.000,76786.000,37950.000,3979,...,5.300,968.000,1984,26554,26523,31.500,146900.000,211500.000,286400.000,2167
1,19159,2.540,1606,7,585,79,57700.000,76250.000,30345.000,809,...,6.200,639.000,1962,1847,1840,29.500,63800.000,111300.000,217600.000,14
2,30009,2.370,3575,19,1547,269,63178.000,82083.000,34108.000,1865,...,5.400,841.000,1981,4500,4494,24.400,187800.000,297500.000,477300.000,367
3,16007,2.960,1927,17,521,81,60337.000,75882.000,25673.000,1637,...,6.400,598.000,1971,2223,2230,26.400,97200.000,160200.000,270600.000,478
4,55011,2.490,5401,7,1650,136,61167.000,75954.000,35044.000,992,...,6.200,730.000,1971,5505,5505,25.200,106800.000,164500.000,245300.000,138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,53003,2.330,7477,53,2821,499,57263.000,73972.000,37745.000,752,...,6.000,856.000,1976,9278,9255,28.700,155000.000,229300.000,323700.000,865
3217,13043,2.960,3650,0,1288,74,36763.000,47221.000,18268.000,602,...,5.300,653.000,1990,4034,4015,28.000,45000.000,94700.000,203900.000,176
3218,48451,2.620,44500,132,13372,1745,62052.000,76060.000,35420.000,6226,...,5.200,917.000,1977,44554,44344,28.000,89800.000,156600.000,230400.000,2073
3219,39089,2.700,67038,143,15584,4999,72771.000,88792.000,39470.000,6090,...,6.200,894.000,1978,66081,65809,26.300,129500.000,195100.000,284300.000,3439
3220,19193,2.640,43104,564,11034,1643,63061.000,76827.000,34683.000,2825,...,5.900,838.000,1957,39563,39362,25.900,89700.000,139600.000,206500.000,2104

Standard Scaling:

,GEOID,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,vacant_units,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,-0.689,-0.441,-0.066,-0.092,-0.069,-0.143,-0.246,0.274,0.496,-0.083,...,-0.710,0.573,0.157,-0.103,-0.102,0.949,0.514,0.409,0.170,-0.049
1,-0.750,-0.217,-0.309,-0.096,-0.308,-0.225,0.023,0.246,-0.228,-0.349,...,0.993,-0.710,-0.279,-0.312,-0.312,0.495,-0.558,-0.537,-0.286,-0.181
2,-0.084,-0.851,-0.291,-0.095,-0.279,-0.213,0.356,0.552,0.130,-0.261,...,-0.521,0.077,0.097,-0.289,-0.290,-0.664,1.042,1.221,1.433,-0.159
3,-0.944,1.349,-0.306,-0.095,-0.309,-0.224,0.183,0.226,-0.672,-0.280,...,1.372,-0.870,-0.101,-0.308,-0.309,-0.209,-0.127,-0.075,0.065,-0.152
4,1.450,-0.404,-0.274,-0.096,-0.276,-0.221,0.234,0.230,0.219,-0.334,...,0.993,-0.355,-0.101,-0.281,-0.281,-0.482,-0.003,-0.034,-0.103,-0.173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,1.327,-1.000,-0.256,-0.093,-0.241,-0.198,-0.004,0.126,0.476,-0.354,...,0.615,0.136,-0.002,-0.249,-0.249,0.313,0.619,0.577,0.417,-0.129
3217,-1.126,1.349,-0.290,-0.096,-0.287,-0.225,-1.253,-1.276,-1.376,-0.367,...,-0.710,-0.656,0.276,-0.293,-0.294,0.154,-0.801,-0.694,-0.377,-0.171
3218,1.047,0.081,0.081,-0.090,0.073,-0.120,0.288,0.236,0.255,0.106,...,-0.900,0.374,0.018,0.049,0.049,0.154,-0.223,-0.109,-0.201,-0.054
3219,0.473,0.379,0.286,-0.089,0.139,0.085,0.941,0.903,0.640,0.095,...,0.993,0.284,0.038,0.231,0.232,-0.232,0.290,0.255,0.156,0.030
3220,-0.748,0.156,0.069,-0.069,0.004,-0.126,0.349,0.276,0.185,-0.180,...,0.425,0.066,-0.378,0.007,0.007,-0.323,-0.224,-0.270,-0.359,-0.052

Min-Max Scaling:

,GEOID,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,vacant_units,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,0.269,0.241,0.008,0.000,0.010,0.003,0.281,0.363,0.318,0.017,...,0.382,0.308,0.990,0.008,0.008,0.536,0.154,0.157,0.113,0.003
1,0.255,0.257,0.000,0.000,0.001,0.000,0.311,0.360,0.236,0.003,...,0.500,0.168,0.979,0.001,0.001,0.488,0.061,0.074,0.078,0.000
2,0.408,0.211,0.001,0.000,0.002,0.001,0.350,0.393,0.276,0.008,...,0.395,0.254,0.989,0.001,0.001,0.367,0.200,0.228,0.212,0.001
3,0.211,0.371,0.001,0.000,0.001,0.000,0.330,0.358,0.186,0.007,...,0.526,0.151,0.984,0.001,0.001,0.414,0.098,0.114,0.105,0.001
4,0.759,0.244,0.002,0.000,0.002,0.000,0.336,0.358,0.286,0.004,...,0.500,0.207,0.984,0.002,0.002,0.386,0.109,0.118,0.092,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,0.731,0.201,0.002,0.000,0.003,0.001,0.308,0.347,0.315,0.003,...,0.474,0.260,0.986,0.003,0.003,0.469,0.163,0.172,0.133,0.001
3217,0.169,0.371,0.001,0.000,0.001,0.000,0.166,0.192,0.107,0.002,...,0.382,0.174,0.993,0.001,0.001,0.452,0.039,0.060,0.071,0.000
3218,0.667,0.279,0.013,0.000,0.016,0.004,0.342,0.359,0.290,0.026,...,0.368,0.286,0.987,0.013,0.013,0.452,0.090,0.111,0.084,0.003
3219,0.535,0.301,0.020,0.000,0.018,0.012,0.416,0.432,0.334,0.026,...,0.500,0.276,0.987,0.020,0.020,0.412,0.135,0.143,0.112,0.005
3220,0.256,0.285,0.013,0.001,0.013,0.004,0.349,0.363,0.283,0.012,...,0.461,0.253,0.977,0.012,0.012,0.402,0.090,0.097,0.072,0.003

Log Transformed:

,GEOID,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,vacant_units,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,9.912,0.908,10.249,4.443,9.059,7.229,10.884,11.249,10.544,8.289,...,1.668,6.875,7.593,10.187,10.186,3.450,11.898,12.262,12.565,7.681
1,9.861,0.932,7.382,1.946,6.372,4.369,10.963,11.242,10.320,6.696,...,1.825,6.460,7.582,7.521,7.518,3.384,11.064,11.620,12.290,2.639
2,10.309,0.863,8.182,2.944,7.344,5.595,11.054,11.315,10.437,7.531,...,1.686,6.735,7.591,8.412,8.410,3.195,12.143,12.603,13.076,5.905
3,9.681,1.085,7.564,2.833,6.256,4.394,11.008,11.237,10.153,7.401,...,1.856,6.394,7.586,7.707,7.710,3.273,11.485,11.984,12.508,6.170
4,10.915,0.912,8.594,1.946,7.409,4.913,11.021,11.238,10.464,6.900,...,1.825,6.593,7.586,8.613,8.613,3.227,11.579,12.011,12.410,4.927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,10.878,0.846,8.920,3.970,7.945,6.213,10.955,11.211,10.539,6.623,...,1.792,6.752,7.589,9.135,9.133,3.357,11.951,12.343,12.688,6.763
3217,9.476,1.085,8.202,-inf,7.161,4.304,10.512,10.763,9.813,6.400,...,1.668,6.482,7.596,8.303,8.298,3.332,10.714,11.458,12.225,5.170
3218,10.788,0.963,10.703,4.883,9.501,7.465,11.036,11.239,10.475,8.736,...,1.649,6.821,7.589,10.704,10.700,3.332,11.405,11.961,12.348,7.637
3219,10.574,0.993,11.113,4.963,9.654,8.517,11.195,11.394,10.583,8.714,...,1.825,6.796,7.590,11.099,11.095,3.270,11.771,12.181,12.558,8.143
3220,9.862,0.971,10.671,6.335,9.309,7.404,11.052,11.249,10.454,7.946,...,1.775,6.731,7.579,10.586,10.581,3.254,11.404,11.847,12.238,7.652

Log Transformed - SS:

,GEOID,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,vacant_units,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,-0.284,-0.430,0.696,0.447,0.687,0.638,-0.104,0.380,0.614,0.518,...,-0.661,0.740,0.044,0.594,0.596,0.917,0.881,0.751,0.466,0.895
1,-0.348,-0.184,-1.155,-0.495,-1.138,-0.770,0.162,0.356,-0.081,-0.793,...,0.969,-0.757,-0.014,-1.187,-1.187,0.530,-0.624,-0.593,-0.189,-1.655
2,0.214,-0.892,-0.638,-0.118,-0.478,-0.166,0.469,0.612,0.282,-0.106,...,-0.474,0.235,0.033,-0.591,-0.591,-0.581,1.324,1.464,1.681,-0.003
3,-0.574,1.385,-1.037,-0.160,-1.216,-0.758,0.314,0.338,-0.599,-0.213,...,1.291,-0.995,0.007,-1.062,-1.059,-0.123,0.136,0.169,0.330,0.131
4,0.975,-0.389,-0.372,-0.495,-0.434,-0.502,0.358,0.341,0.366,-0.625,...,0.969,-0.277,0.007,-0.457,-0.455,-0.393,0.306,0.226,0.097,-0.497
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,0.928,-1.066,-0.162,0.269,-0.070,0.138,0.135,0.246,0.599,-0.853,...,0.627,0.296,0.023,-0.109,-0.108,0.371,0.977,0.920,0.758,0.431
3217,-0.831,1.385,-0.625,-1.230,-0.602,-0.802,-1.359,-1.330,-1.654,-1.037,...,-0.661,-0.678,0.060,-0.664,-0.666,0.224,-1.256,-0.932,-0.343,-0.375
3218,0.815,0.134,0.989,0.614,0.987,0.754,0.408,0.345,0.400,0.886,...,-0.858,0.545,0.023,0.940,0.940,0.224,-0.009,0.121,-0.051,0.873
3219,0.547,0.442,1.254,0.644,1.091,1.272,0.944,0.891,0.735,0.868,...,0.969,0.455,0.028,1.203,1.204,-0.141,0.652,0.581,0.449,1.129
3220,-0.347,0.216,0.969,1.162,0.856,0.724,0.462,0.380,0.335,0.236,...,0.450,0.221,-0.030,0.861,0.860,-0.235,-0.010,-0.118,-0.312,0.881

Log Transformed - MM:

,GEOID,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,vacant_units,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,0.702,0.370,0.605,0.331,0.663,0.558,0.569,0.658,0.606,0.572,...,0.555,0.583,0.999,0.583,0.583,0.722,0.598,0.560,0.427,0.575
1,0.690,0.390,0.368,0.145,0.466,0.338,0.600,0.655,0.517,0.405,...,0.665,0.408,0.997,0.353,0.353,0.684,0.412,0.399,0.346,0.198
2,0.795,0.333,0.434,0.220,0.537,0.432,0.637,0.683,0.564,0.493,...,0.568,0.524,0.998,0.430,0.430,0.575,0.652,0.645,0.578,0.442
3,0.648,0.517,0.383,0.211,0.458,0.339,0.618,0.653,0.450,0.479,...,0.687,0.380,0.998,0.369,0.369,0.620,0.506,0.490,0.410,0.462
4,0.936,0.373,0.468,0.145,0.542,0.380,0.623,0.654,0.575,0.426,...,0.665,0.464,0.998,0.447,0.448,0.594,0.527,0.497,0.382,0.369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,0.928,0.318,0.495,0.296,0.581,0.480,0.597,0.643,0.604,0.397,...,0.642,0.531,0.998,0.492,0.492,0.669,0.610,0.580,0.463,0.506
3217,0.600,0.517,0.435,0.000,0.524,0.332,0.420,0.471,0.314,0.374,...,0.555,0.417,0.999,0.420,0.420,0.654,0.334,0.359,0.327,0.387
3218,0.907,0.416,0.643,0.364,0.695,0.577,0.629,0.654,0.579,0.619,...,0.542,0.560,0.998,0.628,0.628,0.654,0.488,0.485,0.363,0.572
3219,0.857,0.441,0.677,0.370,0.706,0.658,0.693,0.714,0.622,0.617,...,0.665,0.550,0.998,0.662,0.662,0.618,0.569,0.540,0.425,0.610
3220,0.690,0.422,0.640,0.473,0.681,0.572,0.636,0.658,0.571,0.536,...,0.630,0.522,0.997,0.617,0.618,0.609,0.488,0.456,0.331,0.573

# Merge Data

In [41]:
github = r'https://raw.githubusercontent.com/mattlibonati/Northwestern-MSDS-Capstone-2023/main/Data/'

fhfa   = pd.read_csv(github+'fhfa.csv').drop(columns = ['Unnamed: 0'])
fred   = pd.read_csv(github+'fred.csv').drop(columns = ['Unnamed: 0'])
census = pd.read_csv(github+'census.csv')
redfin = pd.read_csv(github+'redfin.csv').drop(columns = ['Unnamed: 0','period_begin'])

display(fhfa.head())
display(fred.head())
display(census.head())
display(redfin.head())

,year,DV_ENC,DV_ESC,DV_MA,DV_MT,DV_NE,DV_PAC,DV_SA,DV_WNC,DV_WSC,USA
0,2016,192.240,211.780,213.610,300.220,218.140,265.280,231.830,232.140,247.360,231.200
1,2017,203.110,223.240,223.640,325.960,229.720,287.200,246.110,244.120,262.230,245.570
2,2018,214.770,236.590,234.140,352.210,240.650,303.020,260.860,257.810,273.900,259.390
3,2019,226.780,250.070,245.440,378.050,252.270,318.660,276.930,271.310,286.210,273.680
4,2020,252.040,277.790,273.370,429.860,285.020,357.140,308.010,298.590,312.500,304.480

         DATE  MORTGAGE30US    yr-mo
0  2022-12-29         6.420  2022-12
1  2021-12-30         3.110  2021-12
2  2020-12-31         2.670  2020-12
3  2019-12-26         3.740  2019-12
4  2018-12-27         4.550  2018-12

,GEOID,NAME,mean_household_size_owner,transportation_drive_alone,transportation_public,one_person_household,more_than_200k,mhhi,mhhi_family,mhhi_nonfamily,...,median_number_rooms,median_gross_rent,median_year_built,plumbing_complete,kitchen_complete,median_gross_rent_frac_income,lower_quartile_home_value,median_home_value,upper_quartile_home_value,electricity_cost
0,20161,"Riley County, Kansas",2.480,28264,85,8595,1379,53296.000,76786.000,37950.000,...,5.300,968.000,1984,26554,26523,31.500,146900.000,211500.000,286400.000,2167
1,19159,"Ringgold County, Iowa",2.540,1606,7,585,79,57700.000,76250.000,30345.000,...,6.200,639.000,1962,1847,1840,29.500,63800.000,111300.000,217600.000,14
2,30009,"Carbon County, Montana",2.370,3575,19,1547,269,63178.000,82083.000,34108.000,...,5.400,841.000,1981,4500,4494,24.400,187800.000,297500.000,477300.000,367
3,16007,"Bear Lake County, Idaho",2.960,1927,17,521,81,60337.000,75882.000,25673.000,...,6.400,598.000,1971,2223,2230,26.400,97200.000,160200.000,270600.000,478
4,55011,"Buffalo County, Wisconsin",2.490,5401,7,1650,136,61167.000,75954.000,35044.000,...,6.200,730.000,1971,5505,5505,25.200,106800.000,164500.000,245300.000,138

,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,...,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2017-12-31,30,county,5,396,f,"Larimer County, CO",NaN,Colorado,CO,...,-0.190,NaN,NaN,NaN,0.000,-0.333,0.000,"Fort Collins, CO",22660.000,3/19/2023
1,2016-12-31,30,county,5,2932,f,"Orleans County, VT",NaN,Vermont,VT,...,-0.041,0.068,-0.037,0.019,0.000,0.000,-0.222,Vermont nonmetropolitan area,NaN,3/19/2023
2,2020-12-31,30,county,5,1396,f,"Mackinac County, MI",NaN,Michigan,MI,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,Michigan nonmetropolitan area,NaN,3/19/2023
3,2019-12-31,30,county,5,888,f,"Starke County, IN",NaN,Indiana,IN,...,0.140,NaN,NaN,NaN,0.083,0.083,0.083,Indiana nonmetropolitan area,NaN,3/19/2023
4,2019-12-31,30,county,5,1012,f,"Butler County, KS",NaN,Kansas,KS,...,1.000,NaN,NaN,NaN,0.000,0.000,NaN,"Wichita, KS",48620.000,3/19/2023

# Functions

Scaling Functions

In [4]:
# Sklearn standardscaler library
# also look at min-max scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler

def scale_set(df):
    x = df.loc[:, :].values
    x_ss = pd.DataFrame(StandardScaler().fit_transform(x), columns = df.columns)
    x_mm = pd.DataFrame(MinMaxScaler().fit_transform(x), columns = df.columns)
    return x_ss, x_mm

Log Transformations

In [5]:
import numpy as np

def log_transform(df):
    df_log = df.copy()
    for col in df_log.columns:
        df_log[col] = round(np.log(df_log[col]),3)
    return df_log

Label Encoding

In [6]:
###################################
# label encoded dataset 
from sklearn import preprocessing

def label_encode(data):
    label_encoder = preprocessing.LabelEncoder()

    label_encoded_df = data.copy()

    for col in label_encoded_df.columns:
        label_encoded_df[col]= label_encoder.fit_transform(label_encoded_df[col])

    label_encoded_df = label_encoded_df.fillna(0)

    return label_encoded_df